import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import PageNavbar from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import StarsCanvas from "@/components/global/stars";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// TODO: Edit description
export const metadata: Metadata = {
  title: "Abhishek Gawande - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased transition-all bg-transparent`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <PageNavbar />
            {children}
            <StarsCanvas />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
